yarray: []
mpaginate: 3
year: 2016
author: 'Rafael Picanço'
url: http://www.rafael.picanco.nom.br
exclude: ['.gitignore',
          'CNAME',
          'cpicanco.github.io.sublime-project',
          'cpicanco.github.io.sublime-workspace',
          'Gemfile',
          'Gemfile.lock',
          'Gruntfile.js',
          'LICENSE.md',
          'README.md',
          'package.json',
          'css/src/',
          'css/min/',
          'js/src/',
          'node_modules/',
          'python/',
          'vendor',
          'tests.html'
          ]
defaults:
  -
    scope:
      path: ""
    values:
      author: 'Rafael Picanço'

  -
    scope:
      path: ""
      type: posts
    values:
      layout: "Post"
  -
    scope:
      path: 'blog/pt-br'
    values:
      language: pt-BR

  -
    scope:
      path: 'portfolio/pt-br'
    values:
      language: pt-BR
  -
    scope:
      path: 'blog/en'
    values:
      language: en

  -
    scope:
      path: 'portfolio/en'
    values:
      language: en

  -
    scope:
      path: 'blog/en/page'
    values:
      layout: Page
      sitemap: false

  -
    scope:
      path: 'blog/pt-br/page'
    values:
      layout: Page
      sitemap: false

gems:
  - jemoji